// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebExample {
	
	
	public partial class SecSignID {
		
		protected System.Web.UI.HtmlControls.HtmlForm CheckAuthSessionForm;
		
		protected System.Web.UI.WebControls.Label lblMessage;
		
		protected System.Web.UI.WebControls.HiddenField requestid;
		
		protected System.Web.UI.WebControls.HiddenField secsignid;
		
		protected System.Web.UI.WebControls.HiddenField authsessionid;
		
		protected System.Web.UI.WebControls.HiddenField servicename;
		
		protected System.Web.UI.WebControls.HiddenField serviceaddress;
		
		protected System.Web.UI.WebControls.HiddenField authsessionicondata;
		
		protected System.Web.UI.HtmlControls.HtmlImage authSessionIconDisplay;
		
		protected System.Web.UI.WebControls.Button cancelauthsession;
		
		protected System.Web.UI.WebControls.Button checkauthsession;
	}
}
